name: Run Cypress Tests

on:
  push:
    branches:
      - main
      - e2e/*
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Cypress
        run: npm install cypress@^13.10.0

      - name: Print Node.js version
        run: node --version
      
      - name: Check Cypress binary permissions
        run: ls -l node_modules/.bin/cypress

      - name: Print Cypress version
        run: ./node_modules/.bin/cypress --version
      

      - name: Print Cypress version
        run: npx cypress --version

      - name: Run Cypress tests
        run: npx cypress run

